// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service/sms/failover/failover_new.go
//
// Generated by this command:
//
//	mockgen -source=./internal/service/sms/failover/failover_new.go -package=smsmocks -destination=./internal/service/mocks/sms/type.mock.go
//
// Package smsmocks is a generated GoMock package.
package smsmocks
