db:
  dsn: "root:root@tcp(localhost:13316)/webook"

redis:
  addr: "localhost:6379"

kafka:
  addr:
    - "localhost:9094"

grpc:
  server:
    etcdAddr: "localhost:12379"
    port: 8090
    name: "interactive"