db:
  dsn: "root:root@tcp(localhost:13316)/webook"

redis:
  addr: "localhost:6379"

kafka:
  addr:
    - "localhost:9094"

grpc:
  client:
    intr:
      addr: "localhost:8090"
      secure: false
#      全部都走grpc调用
      threshold: 100

test: "hello,abcd"